[package]
name = "y10n"
version = "0.1.0"
edition = "2018"
description = "A simple YAML-based localization library"

[dependencies]
# Used for traversing directory structures
glob = "0"
lazy_static = "1"
log = "*"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
regex = "1"
